name: tekartik_jquery_asset
version: 3.1.1+1

description: jquery asset for dart
publish_to: none
environment:
  sdk: '>=2.18.0 <4.0.0'
# dependencies:
#  browser: any
dev_dependencies:
  dev_test:
  lints:
