name: tekartik_jquery_asset
version: 3.1.1+1

description: jquery asset for dart
publish_to: none
environment:
  sdk: '>=3.4.0-0 <4.0.0'
# dependencies:
#  browser: any
dev_dependencies:
  dev_build:
  lints:
  tekartik_lints:
    git:
      url: https://github.com/tekartik/common.dart
      ref: dart3a
      path: packages/lints
    version: '>=0.1.0'